name: automerge
on:
  pull_request_target:
    types:
    - labeled
    - unlabeled
    - synchronize
    - opened
    - edited
    - ready_for_review
    - reopened
    - unlocked
    paths:
      - 'mods/*.json'
      - '!(!mods)/**'
    branches:
      - main
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        fail_on_initial_diff_error: 'true'
    - name: Count changed files
      env: 
        COUNT: ${{ steps.changed-files.outputs.all_changed_and_modified_files_count }}
        DELETED: ${{steps.changed-files.outputs.deleted_files_count}}
      run: |
        if [[ ${COUNT} -gt 1 ]] ; then
          echo "Too many files changed"
          exit 1
        fi
        if [[ ${DELETED} -gt 0 ]] ; then
          echo "Automatic deletion of files is forbidden"
          exit 1
        fi
    - id: automerge
      name: automerge
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GH_TOKEN: ${{github.token}}
